In [97]:
import tensorflow as tf
images_ds = tf.data.Dataset.list_files('TensorFlow/*/*', shuffle=True)
for file in images_ds.take(5):
    print(file.numpy())

b'TensorFlow\\AT&T Fiber\\at-t-fiber-installers-left-cable-exposed-outside-any-ideas-v0-ssdmcmz1439a1.jpg'
b'TensorFlow\\AT&T Fiber\\vwlxds69637b1.jpg'
b'TensorFlow\\iphones\\ios-18-iphone-15-pro-settings-general-software-update-automatic-updates.png'
b'TensorFlow\\iphones\\75205401007-customize-2.jpg'
b'TensorFlow\\iphones\\pexels-photo-818043.jpg'


In [98]:
images_ds = images_ds.shuffle(200)
for file in images_ds.take(7):
    print(file)

tf.Tensor(b'TensorFlow\\iphones\\Download-iPhone-16e-wallpaper.jpg', shape=(), dtype=string)
tf.Tensor(b'TensorFlow\\AT&T Fiber\\how-to-use-your-own-router-with-att-fiber.jpg', shape=(), dtype=string)
tf.Tensor(b'TensorFlow\\AT&T Fiber\\att-fiber-pole-1152x648.jpg', shape=(), dtype=string)
tf.Tensor(b'TensorFlow\\iphones\\ios-13-iphone.jpg', shape=(), dtype=string)
tf.Tensor(b'TensorFlow\\iphones\\2021-09-23-ts3_thumbs-980.jpg', shape=(), dtype=string)
tf.Tensor(b'TensorFlow\\AT&T Fiber\\com_a2d808f0-b34a-4b2b-9612-5a5f89699832_answers_4f7120d9-c0fe-4fe8-9be4-5c46637816b6_.png', shape=(), dtype=string)
tf.Tensor(b'TensorFlow\\iphones\\iphone_15_hero1.png', shape=(), dtype=string)


In [99]:
class_names = ["iphones","AT&T Fiber"]

In [100]:
image_count = len(images_ds)
print(image_count)

165


In [101]:
train_size = int(image_count*0.8)
train_ds = images_ds.take(train_size)
test_ds = images_ds.skip(train_size)

In [102]:
len(train_ds)

132

In [103]:
len(test_ds)

33

In [104]:
s = 'TensorFlow\\AT&T Fiber\\wifi-gateway.jpg'
s.split("\\")

['TensorFlow', 'AT&T Fiber', 'wifi-gateway.jpg']

In [105]:
def get_label(file_path):
    import os
    return tf.strings.split(file_path, os.path.sep)[-2]
    

In [106]:
for t in train_ds.take(2):
    print(t)

tf.Tensor(b'TensorFlow\\AT&T Fiber\\hq720 (2).jpg', shape=(), dtype=string)
tf.Tensor(b'TensorFlow\\iphones\\tWHEq5HUsSpiELwDRh4cu3.jpg', shape=(), dtype=string)


In [107]:
for label in train_ds.map(get_label):
    print(label)

tf.Tensor(b'iphones', shape=(), dtype=string)
tf.Tensor(b'AT&T Fiber', shape=(), dtype=string)
tf.Tensor(b'AT&T Fiber', shape=(), dtype=string)
tf.Tensor(b'AT&T Fiber', shape=(), dtype=string)
tf.Tensor(b'iphones', shape=(), dtype=string)
tf.Tensor(b'iphones', shape=(), dtype=string)
tf.Tensor(b'iphones', shape=(), dtype=string)
tf.Tensor(b'AT&T Fiber', shape=(), dtype=string)
tf.Tensor(b'iphones', shape=(), dtype=string)
tf.Tensor(b'AT&T Fiber', shape=(), dtype=string)
tf.Tensor(b'iphones', shape=(), dtype=string)
tf.Tensor(b'iphones', shape=(), dtype=string)
tf.Tensor(b'AT&T Fiber', shape=(), dtype=string)
tf.Tensor(b'AT&T Fiber', shape=(), dtype=string)
tf.Tensor(b'AT&T Fiber', shape=(), dtype=string)
tf.Tensor(b'iphones', shape=(), dtype=string)
tf.Tensor(b'iphones', shape=(), dtype=string)
tf.Tensor(b'iphones', shape=(), dtype=string)
tf.Tensor(b'iphones', shape=(), dtype=string)
tf.Tensor(b'AT&T Fiber', shape=(), dtype=string)
tf.Tensor(b'iphones', shape=(), dtype=string)
tf.Tens

In [108]:
def process_image(file_path):
    label = get_label(file_path)
    img = tf.io.read_file(file_path)
    img = tf.image.decode_jpeg(img)
    img = tf.image.resize(img, [128,128])

    return img,label

In [109]:
train_ds = train_ds.map(process_image)
for img, label in train_ds.take(3):
    print("Image:",img)
    print("Label:", label)

Image: tf.Tensor(
[[[242.       241.49026  245.01947 ]
  [242.       241.74033  244.51935 ]
  [243.       243.       245.      ]
  ...
  [233.       232.       237.      ]
  [233.       232.       237.      ]
  [233.       232.       237.      ]]

 [[242.       241.       246.      ]
  [242.       242.       243.98438 ]
  [242.78516  242.78516  243.42578 ]
  ...
  [232.78516  231.78516  236.78516 ]
  [232.78516  231.78516  236.78516 ]
  [232.78516  231.78516  236.78516 ]]

 [[242.       242.       244.      ]
  [242.       242.       243.9892  ]
  [241.       241.       241.64062 ]
  ...
  [231.       230.       235.      ]
  [231.       230.       235.      ]
  [231.       230.       235.      ]]

 ...

 [[ 48.147217  54.416748  27.283936]
  [ 25.071808  32.71875   17.443817]
  [ 33.520386  37.223846  23.223846]
  ...
  [ 92.19922  128.8164   140.95074 ]
  [ 87.52185  125.52667  135.75864 ]
  [ 85.64935  123.64935  133.0592  ]]

 [[ 89.96188   99.22714   52.29373 ]
  [ 41.20816   42.1

In [111]:
def scale(image, label):
    return image/255, label

In [112]:
train_ds = train_ds.map(scale)
for image, label in train_ds.take(3):
    print("Image:",image.numpy()[0][0])
    print("Label:",label.numpy())

Image: [0.85882354 0.81960785 0.78431374]
Label: b'AT&T Fiber'
Image: [0.04258578 0.06515012 0.02882966]
Label: b'AT&T Fiber'
Image: [0.1536313  0.13197075 0.13701059]
Label: b'AT&T Fiber'
